'use strict';

// Shared by the pre-contract page and immutable order-confirmation snapshots.
// Bump the version whenever contractual content changes.
const VERSION = 'contract-2026-09-25-v4';
const SECTIONS = Object.freeze([
  { id: 'order', heading: 'Bestellung und Vertragsschluss', text: 'Du gestaltest deine Produkte, legst sie in den Warenkorb und gibst die Lieferadresse an. Die Darstellung im Shop ist noch kein verbindliches Vertragsangebot. Mit dem abschließenden zahlungspflichtigen Bestellbutton bei Stripe gibst du eine verbindliche Bestellung ab. Mit erfolgreichem Abschluss der Zahlung nehmen wir deine Bestellung an; damit kommt der Vertrag zustande. Wir bestätigen ihn anschließend per E-Mail.' },
  { id: 'correction', heading: 'Angaben prüfen und ändern', text: 'Vor der verbindlichen Bestellung kannst du Produkte, Gestaltung, Mengen und Lieferadresse auf unseren Seiten prüfen und ändern. Von Stripe kannst du dafür zum Shop zurückkehren. Bei Änderungen werden Preis und Lieferung erneut geprüft. Das Öffnen der Zahlungsseite allein löst keine Bestellung aus.' },
  { id: 'payment', heading: 'Preise und Zahlung', text: 'Der bei Stripe vor der verbindlichen Bestellung angezeigte Gesamtpreis enthält die berechnete Umsatzsteuer und die ausgewiesenen Versandkosten. Die Zahlung erfolgt per Karte über Stripe; dort verfügbare Karten-Wallets können ebenfalls genutzt werden. Die Zahlung wird im Bestellprozess eingezogen.' },
  { id: 'delivery', heading: 'Herstellung und Lieferung', text: 'Printful stellt die Produkte nach deiner Gestaltung her und versendet sie direkt an die angegebene Lieferadresse. Die für deine Bestellung verfügbare voraussichtliche Lieferzeit zeigen wir vor dem Kauf an und übernehmen sie in die Bestellbestätigung. Produkte können in mehreren Sendungen ankommen. Dein Vertragspartner bleibt JUSA Engineering UG (haftungsbeschränkt).' },
  { id: 'customs', heading: 'Einfuhrkosten', text: 'Bei Lieferungen in bestimmte Länder können zusätzliche Zölle, Einfuhrsteuern oder sonstige Einfuhrgebühren anfallen. Diese sind vom Empfänger zu tragen.' },
  { id: 'withdrawal', heading: 'Personalisierte Produkte und Widerruf', text: 'Die Produkte werden nach deinen individuellen Vorgaben angefertigt. Für Waren, die nicht vorgefertigt sind und für deren Herstellung deine individuelle Auswahl oder Bestimmung maßgeblich ist, besteht grundsätzlich kein gesetzliches Widerrufsrecht (§ 312g Abs. 2 Nr. 1 BGB). Deine gesetzlichen Rechte bei Mängeln bleiben unberührt.' },
  { id: 'cancellation', heading: 'Änderungen, Stornierung und Mängel', text: 'Für Änderungs- oder Stornierungswünsche nach der Bestellung kontaktiere uns möglichst schnell unter kontakt@jusa.io mit deiner Bestellnummer. Wir prüfen, ob die Produktion noch gestoppt oder geändert werden kann; eine freiwillige Stornierung können wir nicht garantieren. Bei beschädigten oder mangelhaften Produkten wende dich ebenfalls an uns. Deine gesetzlichen Mängel- und sonstigen zwingenden Verbraucherrechte bleiben unberührt.' },
  { id: 'storage', heading: 'Vertragstext und Sprachen', text: 'Du kannst auf Deutsch, Englisch, Französisch, Italienisch, Spanisch oder Türkisch bestellen. Maßgeblich für die Bestellbestätigung ist die beim Start der Zahlung gewählte Sprache. Wir speichern die Bestelldaten und den Inhalt der Bestellbestätigung. Diese E-Mail enthält die Vertragsinformationen und kann von dir gespeichert oder ausgedruckt werden. Ein Kundenkonto mit dauerhaftem Zugriff auf den Vertragstext bieten wir nicht an; eine Kopie kannst du unter kontakt@jusa.io anfragen.' },
]);

module.exports = { VERSION, SECTIONS };
