-- Schema-relative Wolkenworte application objects. Keep this migration free
-- of project-global roles, extensions, Cron jobs and Storage declarations so
-- the test suite can apply it safely to one isolated schema per test file.

create table app_schema_versions (
  version     bigint primary key,
  applied_at  timestamptz not null default transaction_timestamp()
);

insert into app_schema_versions (version) values (1);

create table events (
  id              bigint generated by default as identity primary key,
  slug            text not null unique,
  couple_name     text not null,
  admin_pin_hash  text not null,
  admin_pin_salt  text not null,
  locale          text not null default 'de',
  theme           text not null default 'pastel',
  created_at      timestamptz not null,
  expires_at      timestamptz not null,
  constraint events_slug_nonempty check (length(slug) between 1 and 120),
  constraint events_locale_supported check (locale in ('de', 'en', 'fr', 'it', 'es', 'tr')),
  constraint events_expiry_exact check (expires_at = created_at + interval '365 days')
);

create function set_event_expiry()
returns trigger
language plpgsql
as $$
begin
  new.created_at := coalesce(new.created_at, transaction_timestamp());
  new.expires_at := new.created_at + interval '365 days';
  return new;
end
$$;

create trigger events_set_expiry
before insert or update of created_at, expires_at on events
for each row execute function set_event_expiry();

create index events_expires_at_idx on events (expires_at, id);

create table words (
  id          bigint generated by default as identity primary key,
  event_id    bigint not null references events(id) on delete cascade,
  word        text not null,
  count       integer not null default 1,
  updated_at  timestamptz not null default transaction_timestamp(),
  constraint words_count_positive check (count > 0),
  constraint words_event_word_unique unique (event_id, word)
);

create table word_contributions (
  receipt_id  text primary key,
  event_id    bigint not null,
  word        text not null,
  owner_id    text not null,
  created_at  timestamptz not null default transaction_timestamp(),
  constraint word_contributions_word_fk
    foreign key (event_id, word) references words(event_id, word) on delete cascade
);

create index word_contributions_owner_idx
  on word_contributions (event_id, owner_id, created_at, receipt_id);

create table archives (
  id          bigint generated by default as identity primary key,
  event_id    bigint not null references events(id) on delete cascade,
  words_json  jsonb not null,
  created_at  timestamptz not null default transaction_timestamp()
);

create index archives_event_created_idx on archives (event_id, created_at);

create table configurations (
  id                    text primary key,
  event_id              bigint references events(id) on delete restrict,
  product_key           text not null,
  printful_variant_id   integer not null,
  quantity              integer not null default 2,
  unit_price_cents      integer not null default 0,
  theme                 text not null,
  words_json            jsonb not null,
  design_json           jsonb not null,
  configuration_type    text not null default 'event_wordcloud',
  orientation           text not null default 'default',
  print_width           integer not null,
  print_height          integer not null,
  created_at            timestamptz not null default transaction_timestamp(),
  constraint configurations_quantity_valid check (quantity between 1 and 99),
  constraint configurations_dimensions_valid check (print_width > 0 and print_height > 0),
  constraint configurations_type_valid
    check (configuration_type in ('event_wordcloud', 'personal_memory'))
);

create index configurations_event_created_idx
  on configurations (event_id, created_at, id);

create table checkout_quotes (
  id                       text primary key,
  event_id                 bigint not null references events(id) on delete cascade,
  configuration_id         text not null references configurations(id) on delete cascade,
  configuration_ids_json   jsonb,
  recipient_json           jsonb not null,
  shipments_json           jsonb,
  printful_costs_json       jsonb not null,
  currency                 text not null,
  quantity                 integer not null,
  items_cents              integer not null,
  payment_reserve_cents    integer not null default 0,
  shipping_cents           integer not null,
  tax_cents                integer not null,
  total_cents              integer not null,
  expires_at               timestamptz not null,
  created_at               timestamptz not null default transaction_timestamp(),
  updated_at               timestamptz not null default transaction_timestamp(),
  constraint checkout_quotes_quantity_valid check (quantity between 1 and 990),
  constraint checkout_quotes_currency_valid check (currency = upper(currency) and length(currency) = 3),
  constraint checkout_quotes_amounts_valid check (
    items_cents >= 0 and payment_reserve_cents >= 0 and shipping_cents >= 0 and
    tax_cents >= 0 and total_cents >= 0
  )
);

create index checkout_quotes_event_configuration_idx
  on checkout_quotes (event_id, configuration_id);
create index checkout_quotes_expiration_idx
  on checkout_quotes (expires_at, id);

create table orders (
  id                         bigint generated by default as identity primary key,
  event_id                   bigint references events(id) on delete set null,
  event_slug_snapshot        text not null,
  event_label_snapshot       text not null,
  buyer_email                text,
  stripe_session_id          text unique,
  status                     text not null default 'pending',
  shipping_json              jsonb,
  printful_order_id          text,
  fulfillment_status         text not null default 'not_started',
  fulfillment_mode           text,
  fulfillment_attempts       integer not null default 0,
  fulfillment_error          text,
  fulfillment_payload_json   jsonb,
  printful_order_status      text,
  fulfillment_updated_at     timestamptz,
  configuration_id           text references configurations(id) on delete restrict,
  configuration_ids_json     jsonb,
  quote_id                   text,
  currency                   text,
  items_cents                integer,
  payment_reserve_cents      integer not null default 0,
  shipping_cents             integer,
  tax_cents                  integer,
  total_cents                integer,
  stripe_checkout_url        text,
  stripe_payment_intent_id   text,
  stripe_event_id            text,
  mode                       text not null default 'test',
  paid_at                    timestamptz,
  checkout_request_json      jsonb,
  stripe_idempotency_key     text unique,
  checkout_first_attempt_at  timestamptz,
  checkout_last_attempt_at   timestamptz,
  checkout_session_expires_at timestamptz,
  checkout_attempts          integer not null default 0,
  checkout_ambiguous         boolean not null default false,
  checkout_error             text,
  created_at                 timestamptz not null default transaction_timestamp(),
  updated_at                 timestamptz not null default transaction_timestamp(),
  constraint orders_mode_valid check (mode in ('test', 'live')),
  constraint orders_quote_id_unique unique (quote_id),
  constraint orders_buyer_email_length check (buyer_email is null or length(buyer_email) <= 254)
);

create index orders_event_status_idx on orders (event_id, status, id);
create index orders_fulfillment_claim_idx
  on orders (fulfillment_status, fulfillment_attempts, id)
  where status in ('paid_test', 'paid');

create table checkout_order_shipments (
  id                         bigint generated by default as identity primary key,
  order_id                   bigint not null references orders(id) on delete cascade,
  shipment_index             integer not null,
  quantity                   integer not null,
  items_json                 jsonb,
  recipient_json             jsonb not null,
  printful_costs_json         jsonb not null,
  currency                   text not null,
  shipping_cents             integer not null,
  tax_cents                  integer not null,
  fulfillment_status         text not null default 'pending',
  fulfillment_mode           text,
  fulfillment_attempts       integer not null default 0,
  fulfillment_error          text,
  fulfillment_payload_json   jsonb,
  printful_order_id           text,
  printful_order_status       text,
  updated_at                  timestamptz not null default transaction_timestamp(),
  constraint checkout_order_shipments_quantity_valid check (quantity > 0),
  constraint checkout_order_shipments_order_index_unique unique (order_id, shipment_index)
);

create index checkout_order_shipments_fulfillment_idx
  on checkout_order_shipments (fulfillment_status, order_id, shipment_index);

create table order_items (
  id                             bigint generated by default as identity primary key,
  order_id                       bigint not null references orders(id) on delete cascade,
  configuration_id               text references configurations(id) on delete restrict,
  shipment_index                 integer not null,
  item_index                     integer not null,
  product_key                    text not null,
  printful_variant_id            integer not null,
  quantity                       integer not null,
  configuration_snapshot_json    jsonb not null,
  created_at                     timestamptz not null default transaction_timestamp(),
  constraint order_items_quantity_valid check (quantity > 0),
  constraint order_items_order_position_unique unique (order_id, shipment_index, item_index)
);

create index order_items_configuration_idx on order_items (configuration_id, order_id);
create index order_items_order_idx on order_items (order_id, shipment_index, item_index);

create table stripe_webhook_events (
  stripe_event_id    text primary key,
  event_type         text not null,
  stripe_session_id  text,
  order_id           bigint references orders(id) on delete set null,
  processed_at       timestamptz not null default transaction_timestamp()
);

create index stripe_webhook_events_order_idx on stripe_webhook_events (order_id, processed_at);
