-- Operator-only recovery audit records for Phase 8. This migration remains
-- schema-relative so the integration suite can apply it to isolated schemas.

insert into app_schema_versions (version) values (6);

create table operator_actions (
  id              bigint generated by default as identity primary key,
  action_type     text not null,
  order_id        bigint references orders(id) on delete set null,
  before_state    text,
  after_state     text,
  status          text not null default 'running',
  error_code      text,
  summary_json    jsonb,
  created_at      timestamptz not null default transaction_timestamp(),
  completed_at    timestamptz,
  constraint operator_actions_type_valid
    check (action_type in ('manual_fulfillment_retry', 'prelive_cleanup')),
  constraint operator_actions_status_valid
    check (status in ('running', 'succeeded', 'failed')),
  constraint operator_actions_state_length
    check ((before_state is null or length(before_state) <= 80)
      and (after_state is null or length(after_state) <= 80)),
  constraint operator_actions_error_length
    check (error_code is null or length(error_code) <= 120)
);

create index operator_actions_order_idx on operator_actions (order_id, created_at desc);
create index operator_actions_status_idx on operator_actions (status, created_at desc);
