-- Durable transactional email jobs, buyer-contact snapshots and replay-safe
-- Resend delivery state. This migration stays schema-relative for isolated
-- integration-test schemas.

insert into app_schema_versions (version) values (5);

alter table orders
  add column locale_snapshot text not null default 'de',
  add column refunded_at timestamptz,
  add column refunded_cents integer,
  add column canceled_at timestamptz;

update orders target
set locale_snapshot = event.locale
from events event
where target.event_id = event.id;

alter table orders
  add constraint orders_locale_snapshot_valid
    check (locale_snapshot in ('de', 'en', 'fr', 'it', 'es', 'tr')),
  add constraint orders_refunded_cents_valid
    check (refunded_cents is null or refunded_cents >= 0);

alter table checkout_order_shipments
  add column carrier text,
  add column tracking_number text,
  add column tracking_url text;

alter table checkout_order_shipments
  add constraint checkout_order_shipments_carrier_length
    check (carrier is null or length(carrier) <= 120),
  add constraint checkout_order_shipments_tracking_number_length
    check (tracking_number is null or length(tracking_number) <= 200),
  add constraint checkout_order_shipments_tracking_url_length
    check (tracking_url is null or length(tracking_url) <= 2000);

create table email_jobs (
  id                    bigint generated by default as identity primary key,
  order_id              bigint not null references orders(id) on delete restrict,
  shipment_id           bigint references checkout_order_shipments(id) on delete restrict,
  kind                  text not null,
  dedupe_key            text not null unique,
  recipient_email       text,
  locale                text not null,
  template_version      text not null,
  subject               text not null,
  html_body             text not null,
  text_body             text not null,
  status                text not null default 'pending',
  provider_message_id   text unique,
  provider_smoke        boolean not null default false,
  provider_terminal     boolean not null default false,
  provider_event_at     timestamptz,
  delivery_ambiguous    boolean not null default false,
  attempt_count         integer not null default 0,
  next_attempt_at       timestamptz not null default transaction_timestamp(),
  first_send_attempt_at timestamptz,
  locked_by             text,
  locked_until          timestamptz,
  lease_version         integer not null default 0,
  last_error            text,
  sent_at               timestamptz,
  delivered_at          timestamptz,
  bounced_at            timestamptz,
  complained_at         timestamptz,
  created_at            timestamptz not null default transaction_timestamp(),
  updated_at            timestamptz not null default transaction_timestamp(),
  constraint email_jobs_kind_valid check (
    kind in ('order_confirmation', 'shipment_confirmation',
             'refund_confirmation', 'cancellation_confirmation')
  ),
  constraint email_jobs_status_valid check (
    status in ('pending', 'processing', 'sent', 'delivered', 'bounced',
               'complained', 'failed', 'blocked')
  ),
  constraint email_jobs_locale_valid check (locale in ('de', 'en', 'fr', 'it', 'es', 'tr')),
  constraint email_jobs_dedupe_length check (length(dedupe_key) between 1 and 256),
  constraint email_jobs_recipient_length
    check (recipient_email is null or length(recipient_email) <= 254),
  constraint email_jobs_template_version_length check (length(template_version) between 1 and 80),
  constraint email_jobs_subject_length check (length(subject) between 1 and 998),
  constraint email_jobs_body_length check (
    length(html_body) between 1 and 500000 and length(text_body) between 1 and 200000
  ),
  constraint email_jobs_attempt_count_valid check (attempt_count >= 0),
  constraint email_jobs_lease_version_valid check (lease_version >= 0),
  constraint email_jobs_lock_pair check ((locked_by is null) = (locked_until is null)),
  constraint email_jobs_last_error_length check (last_error is null or length(last_error) <= 240)
);

create index email_jobs_claim_idx
  on email_jobs (next_attempt_at, locked_until, id)
  where status in ('pending', 'failed', 'processing') and provider_terminal = false;
create index email_jobs_order_idx on email_jobs (order_id, kind, id);
create index email_jobs_shipment_idx on email_jobs (shipment_id, kind, id);

create table resend_webhook_events (
  svix_id             text primary key,
  event_type         text not null,
  event_created_at   timestamptz,
  email_job_id       bigint references email_jobs(id) on delete set null,
  provider_message_id text,
  processed_at       timestamptz not null default transaction_timestamp(),
  constraint resend_webhook_events_svix_id_length check (length(svix_id) between 1 and 200),
  constraint resend_webhook_events_type_length check (length(event_type) between 1 and 80),
  constraint resend_webhook_events_provider_id_length
    check (provider_message_id is null or length(provider_message_id) <= 200)
);

create index resend_webhook_events_job_idx
  on resend_webhook_events (email_job_id, processed_at desc);

create table email_smoke_runs (
  id            bigint generated by default as identity primary key,
  order_id      bigint references orders(id) on delete set null,
  email_job_id  bigint references email_jobs(id) on delete set null,
  status        text not null,
  outcome_code  text,
  created_at    timestamptz not null default transaction_timestamp(),
  completed_at  timestamptz,
  constraint email_smoke_runs_status_valid check (status in ('running', 'succeeded', 'failed')),
  constraint email_smoke_runs_outcome_length check (outcome_code is null or length(outcome_code) <= 120)
);
