-- Complete Wolkenworte baseline. Application objects are schema-relative so
-- tests can apply this same file inside isolated schemas. Project-global
-- Supabase roles, Storage and Cron setup runs only when the active schema is
-- public.

create table app_schema_versions (
  version     bigint primary key,
  applied_at  timestamptz not null default transaction_timestamp()
);

insert into app_schema_versions (version) values (1);

create table events (
  id              bigint generated by default as identity primary key,
  slug            text not null unique,
  couple_name     text not null,
  event_label     text,
  admin_pin_hash  text,
  admin_pin_salt  text,
  locale          text not null default 'de',
  theme           text not null default 'pastel',
  is_draft        boolean not null default false,
  draft_owner_hash text,
  created_at      timestamptz not null,
  expires_at      timestamptz not null,
  constraint events_slug_valid check (slug ~ '^[A-Za-z0-9_-]{21}[AEIMQUYcgkosw048]$'),
  constraint events_locale_supported check (locale in ('de', 'en', 'fr', 'it', 'es', 'tr')),
  constraint events_expiry_exact check (expires_at = created_at + interval '365 days')
);

create function set_event_expiry()
returns trigger
language plpgsql
as $$
begin
  new.created_at := coalesce(new.created_at, transaction_timestamp());
  new.expires_at := new.created_at + interval '365 days';
  return new;
end
$$;

create trigger events_set_expiry
before insert or update of created_at, expires_at on events
for each row execute function set_event_expiry();

create index events_expires_at_idx on events (expires_at, id);
create index events_draft_owner_idx on events (id, draft_owner_hash)
  where is_draft = true;

create table words (
  id          bigint generated by default as identity primary key,
  event_id    bigint not null references events(id) on delete cascade,
  word        text not null,
  count       integer not null default 1,
  updated_at  timestamptz not null default transaction_timestamp(),
  constraint words_count_positive check (count > 0),
  constraint words_event_word_unique unique (event_id, word)
);

create table word_contributions (
  receipt_id  text primary key,
  event_id    bigint not null,
  word        text not null,
  owner_id    text not null,
  created_at  timestamptz not null default transaction_timestamp(),
  constraint word_contributions_word_fk
    foreign key (event_id, word) references words(event_id, word) on delete cascade
);

create index word_contributions_owner_idx
  on word_contributions (event_id, owner_id, created_at, receipt_id);

create table archives (
  id          bigint generated by default as identity primary key,
  event_id    bigint not null references events(id) on delete cascade,
  words_json  jsonb not null,
  created_at  timestamptz not null default transaction_timestamp()
);

create index archives_event_created_idx on archives (event_id, created_at);

-- Event URLs are permanent capabilities and are never reused after expiry.
create table reserved_event_slugs (
  slug                 text primary key,
  original_created_at  timestamptz not null,
  constraint reserved_event_slugs_valid check (slug ~ '^[A-Za-z0-9_-]{21}[AEIMQUYcgkosw048]$')
);

-- Reset brute-force state stores only an HMAC of the normalized source.
create table admin_pin_failures (
  event_id          bigint not null references events(id) on delete cascade,
  source_ip_hash    text not null,
  window_started_at timestamptz not null default transaction_timestamp(),
  failed_attempts   integer not null default 0,
  blocked_until     timestamptz,
  updated_at        timestamptz not null default transaction_timestamp(),
  primary key (event_id, source_ip_hash),
  constraint admin_pin_failures_hash_valid check (source_ip_hash ~ '^[a-f0-9]{64}$'),
  constraint admin_pin_failures_attempts_valid check (failed_attempts between 0 and 5)
);

create index admin_pin_failures_expiry_idx
  on admin_pin_failures (updated_at, event_id);

create table configurations (
  id                    text primary key,
  event_id              bigint references events(id) on delete restrict,
  product_key           text not null,
  printful_variant_id   integer not null,
  quantity              integer not null default 2,
  unit_price_cents      integer not null default 0,
  theme                 text not null,
  words_json            jsonb not null,
  design_json           jsonb not null,
  orientation           text not null default 'default',
  print_width           integer not null,
  print_height          integer not null,
  created_at            timestamptz not null default transaction_timestamp(),
  expires_at            timestamptz not null,
  constraint configurations_quantity_valid check (quantity between 1 and 99),
  constraint configurations_dimensions_valid check (print_width > 0 and print_height > 0)
);

create index configurations_event_created_idx
  on configurations (event_id, created_at, id);
create index configurations_expiry_idx
  on configurations (expires_at, event_id, id);

create table checkout_quotes (
  id                       text primary key,
  event_id                 bigint not null references events(id) on delete cascade,
  configuration_id         text not null references configurations(id) on delete cascade,
  configuration_ids_json   jsonb,
  recipient_json           jsonb not null,
  shipments_json           jsonb,
  printful_costs_json       jsonb not null,
  currency                 text not null,
  quantity                 integer not null,
  items_cents              integer not null,
  payment_reserve_cents    integer not null default 0,
  shipping_cents           integer not null,
  tax_cents                integer not null,
  total_cents              integer not null,
  expires_at               timestamptz not null,
  created_at               timestamptz not null default transaction_timestamp(),
  updated_at               timestamptz not null default transaction_timestamp(),
  constraint checkout_quotes_quantity_valid check (quantity between 1 and 990),
  constraint checkout_quotes_currency_valid check (currency = upper(currency) and length(currency) = 3),
  constraint checkout_quotes_amounts_valid check (
    items_cents >= 0 and payment_reserve_cents >= 0 and shipping_cents >= 0 and
    tax_cents >= 0 and total_cents >= 0
  )
);

create index checkout_quotes_event_configuration_idx
  on checkout_quotes (event_id, configuration_id);
create index checkout_quotes_expiration_idx
  on checkout_quotes (expires_at, id);

create table orders (
  id                         bigint generated by default as identity primary key,
  event_id                   bigint references events(id) on delete set null,
  event_slug_snapshot        text not null,
  event_label_snapshot       text not null,
  buyer_email                text,
  stripe_session_id          text unique,
  status                     text not null default 'pending',
  shipping_json              jsonb,
  printful_order_id          text,
  fulfillment_status         text not null default 'not_started',
  fulfillment_mode           text,
  fulfillment_attempts       integer not null default 0,
  fulfillment_error          text,
  fulfillment_payload_json   jsonb,
  printful_order_status      text,
  fulfillment_updated_at     timestamptz,
  fulfillment_next_attempt_at timestamptz not null default transaction_timestamp(),
  fulfillment_locked_by      text,
  fulfillment_locked_until   timestamptz,
  fulfillment_lease_version  integer not null default 0,
  fulfillment_submitted_at   timestamptz,
  provider_smoke             boolean not null default false,
  configuration_id           text references configurations(id) on delete restrict,
  configuration_ids_json     jsonb,
  quote_id                   text,
  currency                   text,
  items_cents                integer,
  payment_reserve_cents      integer not null default 0,
  shipping_cents             integer,
  tax_cents                  integer,
  total_cents                integer,
  stripe_checkout_url        text,
  stripe_payment_intent_id   text,
  stripe_event_id            text,
  mode                       text not null default 'test',
  locale_snapshot            text not null default 'de',
  paid_at                    timestamptz,
  refunded_at                timestamptz,
  refunded_cents             integer,
  canceled_at                timestamptz,
  checkout_request_json      jsonb,
  stripe_idempotency_key     text unique,
  checkout_first_attempt_at  timestamptz,
  checkout_last_attempt_at   timestamptz,
  checkout_session_expires_at timestamptz,
  checkout_attempts          integer not null default 0,
  checkout_ambiguous         boolean not null default false,
  checkout_error             text,
  created_at                 timestamptz not null default transaction_timestamp(),
  updated_at                 timestamptz not null default transaction_timestamp(),
  constraint orders_mode_valid check (mode in ('test', 'live')),
  constraint orders_quote_id_unique unique (quote_id),
  constraint orders_buyer_email_length check (buyer_email is null or length(buyer_email) <= 254),
  constraint orders_fulfillment_lease_version_valid check (fulfillment_lease_version >= 0),
  constraint orders_fulfillment_lock_pair
    check ((fulfillment_locked_by is null) = (fulfillment_locked_until is null)),
  constraint orders_locale_snapshot_valid
    check (locale_snapshot in ('de', 'en', 'fr', 'it', 'es', 'tr')),
  constraint orders_refunded_cents_valid check (refunded_cents is null or refunded_cents >= 0)
);

create index orders_event_status_idx on orders (event_id, status, id);
create index orders_fulfillment_claim_idx
  on orders (fulfillment_next_attempt_at, fulfillment_locked_until, id)
  where status in ('paid_test', 'paid')
    and fulfillment_status in ('pending', 'failed', 'processing');

create table checkout_order_shipments (
  id                         bigint generated by default as identity primary key,
  order_id                   bigint not null references orders(id) on delete cascade,
  shipment_index             integer not null,
  quantity                   integer not null,
  items_json                 jsonb,
  recipient_json             jsonb not null,
  printful_costs_json         jsonb not null,
  currency                   text not null,
  shipping_cents             integer not null,
  tax_cents                  integer not null,
  fulfillment_status         text not null default 'pending',
  fulfillment_mode           text,
  fulfillment_attempts       integer not null default 0,
  fulfillment_error          text,
  fulfillment_payload_json   jsonb,
  printful_order_id           text,
  printful_order_status       text,
  provider_shipment_id        text,
  fulfillment_submitted_at    timestamptz,
  shipped_at                  timestamptz,
  delivered_at                timestamptz,
  carrier                     text,
  tracking_number             text,
  tracking_url                text,
  updated_at                  timestamptz not null default transaction_timestamp(),
  constraint checkout_order_shipments_quantity_valid check (quantity > 0),
  constraint checkout_order_shipments_order_index_unique unique (order_id, shipment_index),
  constraint checkout_order_shipments_carrier_length
    check (carrier is null or length(carrier) <= 120),
  constraint checkout_order_shipments_tracking_number_length
    check (tracking_number is null or length(tracking_number) <= 200),
  constraint checkout_order_shipments_tracking_url_length
    check (tracking_url is null or length(tracking_url) <= 2000)
);

create index checkout_order_shipments_fulfillment_idx
  on checkout_order_shipments (fulfillment_status, order_id, shipment_index);

create table order_items (
  id                             bigint generated by default as identity primary key,
  order_id                       bigint not null references orders(id) on delete cascade,
  configuration_id               text references configurations(id) on delete restrict,
  shipment_index                 integer not null,
  item_index                     integer not null,
  product_key                    text not null,
  printful_variant_id            integer not null,
  quantity                       integer not null,
  configuration_snapshot_json    jsonb not null,
  created_at                     timestamptz not null default transaction_timestamp(),
  constraint order_items_quantity_valid check (quantity > 0),
  constraint order_items_order_position_unique unique (order_id, shipment_index, item_index)
);

create index order_items_configuration_idx on order_items (configuration_id, order_id);
create index order_items_order_idx on order_items (order_id, shipment_index, item_index);

create table stripe_webhook_events (
  stripe_event_id    text primary key,
  event_type         text not null,
  stripe_session_id  text,
  order_id           bigint references orders(id) on delete set null,
  processed_at       timestamptz not null default transaction_timestamp()
);

create index stripe_webhook_events_order_idx on stripe_webhook_events (order_id, processed_at);

create table print_artifacts (
  id                    text primary key,
  order_id              bigint not null references orders(id) on delete restrict,
  order_item_id         bigint not null references order_items(id) on delete restrict,
  configuration_id      text references configurations(id) on delete set null,
  surface_key           text not null,
  object_key            text not null unique,
  mime_type             text not null,
  byte_size             integer not null,
  sha256                text not null,
  access_nonce          text not null,
  storage_status        text not null default 'uploading',
  deletion_attempts     integer not null default 0,
  last_upload_error     text,
  last_delete_error     text,
  support_hold          boolean not null default false,
  created_at            timestamptz not null default transaction_timestamp(),
  expires_at            timestamptz not null,
  deleted_at            timestamptz,
  constraint print_artifacts_order_item_surface_unique unique (order_item_id, surface_key),
  constraint print_artifacts_id_valid check (id ~ '^[A-Za-z0-9_-]{24}$'),
  constraint print_artifacts_nonce_valid check (access_nonce ~ '^[A-Za-z0-9_-]{32}$'),
  constraint print_artifacts_surface_valid check (surface_key ~ '^[a-z0-9_-]{1,32}$'),
  constraint print_artifacts_mime_valid check (mime_type in ('image/svg+xml', 'image/png')),
  constraint print_artifacts_size_valid check (byte_size between 1 and 25165824),
  constraint print_artifacts_sha_valid check (sha256 ~ '^[a-f0-9]{64}$'),
  constraint print_artifacts_status_valid
    check (storage_status in ('uploading', 'active', 'deleting', 'delete_failed')),
  constraint print_artifacts_attempts_valid check (deletion_attempts >= 0),
  constraint print_artifacts_upload_error_length
    check (last_upload_error is null or length(last_upload_error) <= 240),
  constraint print_artifacts_delete_error_length
    check (last_delete_error is null or length(last_delete_error) <= 240)
);

create index print_artifacts_order_idx on print_artifacts (order_id, order_item_id, surface_key);
create index print_artifacts_cleanup_idx
  on print_artifacts (support_hold, storage_status, expires_at, id);

create table maintenance_runs (
  id            bigint generated by default as identity primary key,
  trigger_kind  text not null default 'http',
  status        text not null default 'running',
  summary_json  jsonb,
  error_code    text,
  started_at    timestamptz not null default transaction_timestamp(),
  completed_at  timestamptz,
  constraint maintenance_runs_trigger_valid check (trigger_kind in ('http', 'manual', 'test')),
  constraint maintenance_runs_status_valid check (status in ('running', 'succeeded', 'failed')),
  constraint maintenance_runs_error_length check (error_code is null or length(error_code) <= 120)
);

create index maintenance_runs_completion_idx on maintenance_runs (completed_at desc, id desc);

create table printful_webhook_events (
  event_key          text primary key,
  event_type         text not null,
  provider_order_id  text,
  external_order_id  text,
  processed_at       timestamptz not null default transaction_timestamp(),
  constraint printful_webhook_events_key_valid check (event_key ~ '^[a-f0-9]{64}$'),
  constraint printful_webhook_events_type_length check (length(event_type) between 1 and 80)
);

create index printful_webhook_events_order_idx
  on printful_webhook_events (external_order_id, processed_at desc);

create table provider_smoke_runs (
  id            bigint generated by default as identity primary key,
  order_id      bigint references orders(id) on delete set null,
  product_key   text not null,
  status        text not null,
  outcome_code  text,
  created_at    timestamptz not null default transaction_timestamp(),
  completed_at  timestamptz,
  constraint provider_smoke_runs_status_valid check (status in ('running', 'succeeded', 'failed')),
  constraint provider_smoke_runs_outcome_length check (outcome_code is null or length(outcome_code) <= 120)
);

create table email_jobs (
  id                    bigint generated by default as identity primary key,
  order_id              bigint not null references orders(id) on delete restrict,
  shipment_id           bigint references checkout_order_shipments(id) on delete restrict,
  kind                  text not null,
  dedupe_key            text not null unique,
  recipient_email       text,
  locale                text not null,
  template_version      text not null,
  subject               text not null,
  html_body             text not null,
  text_body             text not null,
  status                text not null default 'pending',
  provider_message_id   text unique,
  provider_smoke        boolean not null default false,
  provider_terminal     boolean not null default false,
  provider_event_at     timestamptz,
  delivery_ambiguous    boolean not null default false,
  attempt_count         integer not null default 0,
  next_attempt_at       timestamptz not null default transaction_timestamp(),
  first_send_attempt_at timestamptz,
  locked_by             text,
  locked_until          timestamptz,
  lease_version         integer not null default 0,
  last_error            text,
  sent_at               timestamptz,
  delivered_at          timestamptz,
  bounced_at            timestamptz,
  complained_at         timestamptz,
  created_at            timestamptz not null default transaction_timestamp(),
  updated_at            timestamptz not null default transaction_timestamp(),
  constraint email_jobs_kind_valid check (
    kind in ('order_confirmation', 'shipment_confirmation',
             'refund_confirmation', 'cancellation_confirmation')
  ),
  constraint email_jobs_status_valid check (
    status in ('pending', 'processing', 'sent', 'delivered', 'bounced',
               'complained', 'failed', 'blocked')
  ),
  constraint email_jobs_locale_valid check (locale in ('de', 'en', 'fr', 'it', 'es', 'tr')),
  constraint email_jobs_dedupe_length check (length(dedupe_key) between 1 and 256),
  constraint email_jobs_recipient_length
    check (recipient_email is null or length(recipient_email) <= 254),
  constraint email_jobs_template_version_length check (length(template_version) between 1 and 80),
  constraint email_jobs_subject_length check (length(subject) between 1 and 998),
  constraint email_jobs_body_length check (
    length(html_body) between 1 and 500000 and length(text_body) between 1 and 200000
  ),
  constraint email_jobs_attempt_count_valid check (attempt_count >= 0),
  constraint email_jobs_lease_version_valid check (lease_version >= 0),
  constraint email_jobs_lock_pair check ((locked_by is null) = (locked_until is null)),
  constraint email_jobs_last_error_length check (last_error is null or length(last_error) <= 240)
);

create index email_jobs_claim_idx
  on email_jobs (next_attempt_at, locked_until, id)
  where status in ('pending', 'failed', 'processing') and provider_terminal = false;
create index email_jobs_order_idx on email_jobs (order_id, kind, id);
create index email_jobs_shipment_idx on email_jobs (shipment_id, kind, id);

create table resend_webhook_events (
  svix_id              text primary key,
  event_type           text not null,
  event_created_at     timestamptz,
  email_job_id         bigint references email_jobs(id) on delete set null,
  provider_message_id  text,
  processed_at         timestamptz not null default transaction_timestamp(),
  constraint resend_webhook_events_svix_id_length check (length(svix_id) between 1 and 200),
  constraint resend_webhook_events_type_length check (length(event_type) between 1 and 80),
  constraint resend_webhook_events_provider_id_length
    check (provider_message_id is null or length(provider_message_id) <= 200)
);

create index resend_webhook_events_job_idx
  on resend_webhook_events (email_job_id, processed_at desc);

create table email_smoke_runs (
  id            bigint generated by default as identity primary key,
  order_id      bigint references orders(id) on delete set null,
  email_job_id  bigint references email_jobs(id) on delete set null,
  status        text not null,
  outcome_code  text,
  created_at    timestamptz not null default transaction_timestamp(),
  completed_at  timestamptz,
  constraint email_smoke_runs_status_valid check (status in ('running', 'succeeded', 'failed')),
  constraint email_smoke_runs_outcome_length check (outcome_code is null or length(outcome_code) <= 120)
);

create table operator_actions (
  id              bigint generated by default as identity primary key,
  action_type     text not null,
  order_id        bigint references orders(id) on delete set null,
  before_state    text,
  after_state     text,
  status          text not null default 'running',
  error_code      text,
  summary_json    jsonb,
  created_at      timestamptz not null default transaction_timestamp(),
  completed_at    timestamptz,
  constraint operator_actions_type_valid
    check (action_type in ('manual_fulfillment_retry', 'prelive_cleanup')),
  constraint operator_actions_status_valid check (status in ('running', 'succeeded', 'failed')),
  constraint operator_actions_state_length check (
    (before_state is null or length(before_state) <= 80)
    and (after_state is null or length(after_state) <= 80)
  ),
  constraint operator_actions_error_length check (error_code is null or length(error_code) <= 120)
);

create index operator_actions_order_idx on operator_actions (order_id, created_at desc);
create index operator_actions_status_idx on operator_actions (status, created_at desc);

-- Project-global Supabase boundary. Isolated test schemas stop here.
do $global_setup$
declare
  table_name text;
begin
  if current_schema() <> 'public' then
    return;
  end if;

  if not exists (select 1 from pg_roles where rolname = 'wolkenworte_runtime') then
    create role wolkenworte_runtime
      nologin nosuperuser nocreatedb nocreaterole noinherit;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'wolkenworte_app') then
    create role wolkenworte_app
      nologin nosuperuser nocreatedb nocreaterole inherit;
  end if;

  execute 'grant wolkenworte_runtime to wolkenworte_app';
  execute 'alter role wolkenworte_app set search_path = public';
  execute 'alter role wolkenworte_app set statement_timeout = ''10s''';
  execute 'alter role wolkenworte_app set lock_timeout = ''5s''';
  execute 'revoke create on schema public from public';
  execute 'revoke create on schema public from wolkenworte_runtime';
  execute 'revoke create on schema public from wolkenworte_app';

  foreach table_name in array array[
    'app_schema_versions',
    'events',
    'words',
    'word_contributions',
    'archives',
    'reserved_event_slugs',
    'admin_pin_failures',
    'configurations',
    'checkout_quotes',
    'orders',
    'checkout_order_shipments',
    'order_items',
    'stripe_webhook_events',
    'print_artifacts',
    'maintenance_runs',
    'printful_webhook_events',
    'provider_smoke_runs',
    'email_jobs',
    'resend_webhook_events',
    'email_smoke_runs',
    'operator_actions'
  ]
  loop
    execute format(
      'grant select, insert, update, delete on table public.%I to wolkenworte_runtime',
      table_name
    );
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop policy if exists wolkenworte_runtime_all on public.%I', table_name);
    execute format(
      'create policy wolkenworte_runtime_all on public.%I for all to wolkenworte_runtime using (true) with check (true)',
      table_name
    );
  end loop;

  execute 'grant usage on schema public to wolkenworte_runtime';
  execute 'grant usage, select on all sequences in schema public to wolkenworte_runtime';
  execute 'grant execute on all functions in schema public to wolkenworte_runtime';
  execute 'alter default privileges in schema public grant select, insert, update, delete on tables to wolkenworte_runtime';
  execute 'alter default privileges in schema public grant usage, select on sequences to wolkenworte_runtime';
  execute 'alter default privileges in schema public grant execute on functions to wolkenworte_runtime';
  execute 'revoke all on table public.wolkenworte_migrations from wolkenworte_runtime';

  if to_regclass('storage.buckets') is null then
    raise exception 'Supabase Storage schema is missing';
  end if;
  insert into storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
  ) values (
    'wolkenworte-private',
    'wolkenworte-private',
    false,
    25165824,
    array['image/svg+xml', 'image/png']::text[]
  )
  on conflict (id) do update set
    public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

  execute 'create extension if not exists pg_net with schema extensions';
  execute 'create extension if not exists pg_cron with schema pg_catalog';
  execute $maintenance_function$
    create or replace function public.configure_wolkenworte_maintenance_cron()
    returns bigint
    language plpgsql
    security definer
    set search_path = public, vault, cron, net
    as $maintenance_body$
    declare
      maintenance_url text;
      maintenance_secret text;
      scheduled_job_id bigint;
    begin
      select decrypted_secret into maintenance_url
      from vault.decrypted_secrets where name = 'wolkenworte_maintenance_url';
      select decrypted_secret into maintenance_secret
      from vault.decrypted_secrets where name = 'wolkenworte_maintenance_secret';
      if maintenance_url is null or maintenance_secret is null then
        raise exception 'Wolkenworte maintenance Vault secrets are missing';
      end if;

      perform cron.unschedule(jobid)
      from cron.job where jobname = 'wolkenworte-maintenance';

      select cron.schedule(
        'wolkenworte-maintenance',
        '*/5 * * * *',
        $request$
          select net.http_post(
            url := (
              select decrypted_secret from vault.decrypted_secrets
              where name = 'wolkenworte_maintenance_url'
            ),
            headers := jsonb_build_object(
              'Content-Type', 'application/json',
              'Authorization', 'Bearer ' || (
                select decrypted_secret from vault.decrypted_secrets
                where name = 'wolkenworte_maintenance_secret'
              )
            ),
            body := '{}'::jsonb,
            timeout_milliseconds := 30000
          );
        $request$
      ) into scheduled_job_id;
      return scheduled_job_id;
    end
    $maintenance_body$
  $maintenance_function$;
  execute 'revoke all on function public.configure_wolkenworte_maintenance_cron() from public';
  execute 'revoke all on function public.configure_wolkenworte_maintenance_cron() from wolkenworte_runtime';
end
$global_setup$;
