-- Frozen paid print artifacts, leased fulfillment work, maintenance heartbeats
-- and replay-safe Printful webhook state. This file remains schema-relative so
-- the integration suite can apply it inside an isolated test schema.

insert into app_schema_versions (version) values (4);

alter table orders
  add column fulfillment_next_attempt_at timestamptz not null default transaction_timestamp(),
  add column fulfillment_locked_by text,
  add column fulfillment_locked_until timestamptz,
  add column fulfillment_lease_version integer not null default 0,
  add column fulfillment_submitted_at timestamptz,
  add column provider_smoke boolean not null default false;

alter table orders
  add constraint orders_fulfillment_lease_version_valid
    check (fulfillment_lease_version >= 0),
  add constraint orders_fulfillment_lock_pair
    check ((fulfillment_locked_by is null) = (fulfillment_locked_until is null));

drop index orders_fulfillment_claim_idx;
create index orders_fulfillment_claim_idx
  on orders (fulfillment_next_attempt_at, fulfillment_locked_until, id)
  where status in ('paid_test', 'paid')
    and fulfillment_status in ('pending', 'failed', 'processing');

alter table checkout_order_shipments
  add column provider_shipment_id text,
  add column fulfillment_submitted_at timestamptz,
  add column shipped_at timestamptz,
  add column delivered_at timestamptz;

create table print_artifacts (
  id                    text primary key,
  order_id              bigint not null references orders(id) on delete restrict,
  order_item_id         bigint not null references order_items(id) on delete restrict,
  configuration_id      text references configurations(id) on delete set null,
  surface_key           text not null,
  object_key            text not null unique,
  mime_type             text not null,
  byte_size             integer not null,
  sha256                text not null,
  access_nonce          text not null,
  storage_status        text not null default 'uploading',
  deletion_attempts     integer not null default 0,
  last_upload_error     text,
  last_delete_error     text,
  support_hold          boolean not null default false,
  created_at            timestamptz not null default transaction_timestamp(),
  expires_at            timestamptz not null,
  deleted_at            timestamptz,
  constraint print_artifacts_order_item_surface_unique unique (order_item_id, surface_key),
  constraint print_artifacts_id_valid check (id ~ '^[A-Za-z0-9_-]{24}$'),
  constraint print_artifacts_nonce_valid check (access_nonce ~ '^[A-Za-z0-9_-]{32}$'),
  constraint print_artifacts_surface_valid check (surface_key ~ '^[a-z0-9_-]{1,32}$'),
  constraint print_artifacts_mime_valid check (mime_type in ('image/svg+xml', 'image/png')),
  constraint print_artifacts_size_valid check (byte_size between 1 and 25165824),
  constraint print_artifacts_sha_valid check (sha256 ~ '^[a-f0-9]{64}$'),
  constraint print_artifacts_status_valid
    check (storage_status in ('uploading', 'active', 'deleting', 'delete_failed')),
  constraint print_artifacts_attempts_valid check (deletion_attempts >= 0),
  constraint print_artifacts_upload_error_length
    check (last_upload_error is null or length(last_upload_error) <= 240),
  constraint print_artifacts_delete_error_length
    check (last_delete_error is null or length(last_delete_error) <= 240)
);

create index print_artifacts_order_idx on print_artifacts (order_id, order_item_id, surface_key);
create index print_artifacts_cleanup_idx
  on print_artifacts (support_hold, storage_status, expires_at, id);

create table maintenance_runs (
  id            bigint generated by default as identity primary key,
  trigger_kind  text not null default 'http',
  status        text not null default 'running',
  summary_json  jsonb,
  error_code    text,
  started_at    timestamptz not null default transaction_timestamp(),
  completed_at  timestamptz,
  constraint maintenance_runs_trigger_valid check (trigger_kind in ('http', 'manual', 'test')),
  constraint maintenance_runs_status_valid check (status in ('running', 'succeeded', 'failed')),
  constraint maintenance_runs_error_length check (error_code is null or length(error_code) <= 120)
);

create index maintenance_runs_completion_idx on maintenance_runs (completed_at desc, id desc);

create table printful_webhook_events (
  event_key          text primary key,
  event_type         text not null,
  provider_order_id  text,
  external_order_id  text,
  processed_at       timestamptz not null default transaction_timestamp(),
  constraint printful_webhook_events_key_valid check (event_key ~ '^[a-f0-9]{64}$'),
  constraint printful_webhook_events_type_length check (length(event_type) between 1 and 80)
);

create index printful_webhook_events_order_idx
  on printful_webhook_events (external_order_id, processed_at desc);

create table provider_smoke_runs (
  id            bigint generated by default as identity primary key,
  order_id      bigint references orders(id) on delete set null,
  product_key   text not null,
  status        text not null,
  outcome_code  text,
  created_at    timestamptz not null default transaction_timestamp(),
  completed_at  timestamptz,
  constraint provider_smoke_runs_status_valid check (status in ('running', 'succeeded', 'failed')),
  constraint provider_smoke_runs_outcome_length check (outcome_code is null or length(outcome_code) <= 120)
);
